### ISSUE TITLE
Merge with AndreaCrotti/yasnippet-snippets?

### ISSUE THREAD

**Issue by pkkm** [haskell/haskell-snippets#4]
YASnippet's official snippets are at https://github.com/AndreaCrotti/yasnippet-snippets. If we copied the snippets there and obsoleted this repository, they would be available by default to every YASnippet user, instead of only the ones who install an additional package. Do you think it's a good idea, or is it better for the repositories to be separate?

**Comment by purcell** [comment]
It partly depends on how responsive the `yasnippet-snippets` maintainer is to pull requests. But in general, now that we've got a good package system, it makes more sense IMO to have several small packages than one huge one: every time somebody updates a single snippet in the central snippets repo, it will result in a new huge package which all users must install. It's easy for haskell users to install `haskell-snippets`.

**Comment by lukehoersten** [comment]
I agree with @purcell here. We can be more responsive to Haskell users in the current setup. In fact I dislike the monolithic yasnippet defaults because they conflict with my custom snippets and there's no way to disable the defaults afaik.
