### ISSUE TITLE
Implicit dependency cl is no longer required by yasnippet

### ISSUE THREAD

**Issue by cydparser** [haskell/haskell-snippets#6]
_yasnippet_ recently switched to using [_cl-lib_](https://github.com/joaotavora/yasnippet/commit/52643799088eb653e9250b4f04319e5e3e2801a0) (as recommended by the Emacs [manual](https://www.gnu.org/software/emacs/manual/html_mono/cl.html#Organization)). _haskell-snippets_ implicitly depends on _cl.el_. Users who do not load any packages that require _cl_ will see errors like the following:

```
{-# OPTIONS_GHC [yas] elisp error: Symbol's function definition is void: some #-}
```

**Comment by lukehoersten** [comment]
Thanks for the PR and all!
